export class Project{
  title?:string = '';
  title1?:number = 0;
  summary?:string = '';
  class?:number = 0;
  rating?:number = 0;
  evaluationCriteria?:string = '';
  startDate?:string = '';
  endDate?:string = '';
  date?:string = '';
  time?:string = '';
  school?:string = '';
  notes?:string = '';
  presentation_clarity?:number = 0;
  work_quality?:number = 0;
  companionship?:number = 0;
  progression_percentage?:number = 0;
  students?:any[] = [];
  teacherId?:string = '';
  _createdDate?:any = '';
  _id?:string = '';
  _owner?:string = '';
  _updatedDate?:any = '';
}
